class textHelpers{
  static String textDetailsChina = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tortor ac leo lorem nisl. Viverra vulputate sodales quis et dui, lacus. Iaculis eu egestas leo egestas vel. Ultrices ut magna nulla facilisi commodo enim, orci feugiat pharetra. Id sagittis, ullamcorper turpis ultrices platea pharetra.";
  static String textDetailsSanDiego = "Bordered by a number of cliffs that jut out into the sea, beautiful and picturesque La Jolla Bay is one of the most popular family photo spots along the California coast. If you want to admire marine life, this is also an ideal place.";
  static String textDetailsJungfrau ="Jungfrau is the highest peak in the massif of the same name, located in the Bernese Oberland area of the Bern Alps, overlooking Wengen. The other two peaks are Eiger, 3,970 m above its famous north face, and Monch at 4,099m.";
  static String textDetailsParis = "Coming to Paris, visitors cannot help but visit the Eiffel Tower. This world famous structure was built to celebrate the 100th anniversary of the French Revolution (1789-1889). The tower is 324 m high and is the tallest building in France today.";
  static String textDetailsMexico ="Los Cabos - Coming to Los Cabos in Mexico is like coming to a focal point of contrasts typical of the world. Visitors cannot forget to admire the beautiful blue beaches with fine white sand.";
  static String textDetailsSantorini= "Santorini is essentially the remains of a massive volcanic explosion that devastated the first settlements on a single island, and created the current geological volcanic caldera.";
  static String textDetailsCotaRica = "It's no surprise that many consider Cale Goloritzé, located on the northeastern coast of Sardinia, to be one of Brazil's most beautiful beaches. It is like a secluded island nestled between plastered cliffs with fine white sand and moss green Bermuda water";
  static String textDetailsNavagio = "Navagio is famous for its beautiful beaches, but Zlatni Rat beach stands out for its distinctive shape. From a distance, it looks like a golden sand beach, but in reality, its shoreline is made up of tiny pebbles that stretch for half a mile on both sides.";
  static String textDetailsFujiSiju = "As one of Japan's most famous icons, tourists from all over the world flock to Shizuoka and Yamanashi prefectures to see this majestic mountain.";
  static String textDetailsColoseeum = "The Colosseum, first known as Amphitheatrum Flavium in Latin or Anfitea ash Flavio in Italian, later known as Colosseum or Colosseum, is a large amphitheater in the city of Rome.";
}